### ISSUE TITLE
axmol build -p android -a arm64 is not working like descriped

### ISSUE THREAD

**Issue by aismann** [axmolengine/axmol#2173]
docu:
` Android: `axmol build -p android -a arm64` (can run on Windows, Linux and macOS, and script will auto setup Android SDK)`

Tried on windows:
`axmol build -p android -a arm64`

output:
```
axmol: -p android -a arm64 -d: ...
1kiss: PowerShell 7.3.5 on Microsoft Windows 10.0.19045.0
1kiss:
Name                           Value
----                           -----
xb                             {}
scope                          local
xt                             proj.android/gradlew
prefix                         ...\axmol\tools\external
sdk
d                              ...
u                              False
cc
t
xc                             {}
a                              arm64
j                              8
i                              False
p                              android
dm                             False
dll                            False
O                              -1
minsdk


1kiss: proj_dir=C:\Users\..., external_prefix=...\axmol\tools\external
1kiss: Using glslcc: ...\axmol\tools\external\glslcc\glslcc.exe, version: 1.9.5
1kiss: info: the cmd follow symlink ...\axmol\tools\external\cmake\bin\ninja.exe ==> ...\axmol\tools\external\ninja\ninja.exe
1kiss: Using ninja: ...\axmol\tools\external\cmake\bin\ninja.exe, version: 1.10.0
1kiss: info: the cmd follow symlink ...\axmol\tools\external\cmake\bin\ninja.exe ==> ...\axmol\tools\external\ninja\ninja.exe
1kiss: Using jdk: ...\axmol\tools\external\jdk\bin\javac.exe 17.0.12, version: 17.0.12
1kiss: Looking require r23c in ...\axmol\tools\external\adt\sdk
1kiss: Found ...\axmol\tools\external\adt\sdk\ndk\23.2.8568313 in ...\axmol\tools\external\adt\sdk ...
1kiss: Building target android on windows with toolchain clang ...
1kiss: CONFIG_ALL_OPTIONS=-P__1K_CMAKE_VERSION=3.30.2 -P__1K_ARCHS=arm64-v8a --parallel --info -D_1KFETCH_UPGRADE=FALSE, Count=5
Downloading https://services.gradle.org/distributions/gradle-8.10-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)


```

**Comment by halx99** [comment]
should be network issue of your computer

**Comment by aismann** [comment]
Thanks.  I will try it on another machine  again

**Comment by aismann** [comment]
@halx99 
I tested on another machine. Works!
Thanks again for so much easier building android apps now
